### ISSUE TITLE
Optimisation button not running for more than 20 entries on the input dataset

### ISSUE THREAD

**Issue by reginaofori** [langwatch/langwatch#127]
I am unsure why the optimisation button is not running for more than 20 entries on the input dataset.

It was running initially, but not anymore

![Image](https://github.com/user-attachments/assets/99babbde-bdc3-4e2c-8477-671ec32b282b)

**Comment by richhuth** [comment]
@reginaofori Thanks for reporting this issue! We have fixed this, everything should be good to go. Let us know if you run into any further issues.

**Comment by reginaofori** [comment]
@richhuth, many thanks for getting back! 


I tried running the optimisation just now on my 10 dataset entry and it's still the same. The evaluation works on the 10 but the same issue for the oprimisation button

<img width="373" alt="Image" src="https://github.com/user-attachments/assets/ad82c929-6055-4fd6-8869-ebaf43f1dd6d" />

<img width="415" alt="Image" src="https://github.com/user-attachments/assets/962f1e5b-981c-4813-9eb9-3532223da361" />

**Comment by richhuth** [comment]
@reginaofori we actually fixed an issue on the run of the optimization. With regard to the limit, we do expect dataset of more than 20 to get the best result.

**Comment by 0xdeafcafe** [comment]
Closing as resolved.
